apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-ui
      port: {{ .Values.service.httpPort }}
      targetPort: 8025
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - name: tcp-smtp
      port: {{ .Values.service.smtpPort }}
      targetPort: 1025
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.smtp)) }}
      nodePort: {{ .Values.service.nodePorts.smtp }}
      {{- end }}

  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
