{{- if and .Values.adminUser.username .Values.adminUser.password }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-admin
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.adminUser.username | quote }}
  password: {{ .Values.adminUser.password | quote }}
{{- end }}