apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "common.namespace" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}  
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: {{ .Values.store.name }}
    kind: {{ .Values.store.kind }}
  target:
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ "{{ ." }}{{ .Values.source.cert }}{{ " }}" }}"
        tls.key: "{{ "{{ ." }}{{ .Values.source.privkey }}{{ " }}" }}"
  dataFrom:
    - extract:
        key: {{ .Values.source.key }}
