image:
  registry: ghcr.io
  repository: mccutchen/go-httpbin
  tag: 2.18
  pullPolicy: IfNotPresent

# -- Registry secret names as an array
imagePullSecrets: []

# -- String to partially override common.fullname
nameOverride: ""
# -- String to fully override common.fullname
fullnameOverride: ""
# -- Override the namespace
# @default -- `.Release.Namespace`
namespaceOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  # -- Enable ingress record generation
  enabled: false
  className: ""
  # -- Default host for the ingress record (evaluated as template)
  hostname: httpbin.local
  annotations: {}
  # -- Enable TLS configuration for the host defined at ingress.hostname parameter
  tls: false
  # -- Optional custom TLS secret name. If not set, defaults to "<hostname>-tls".
  secretName: ""
